site_name: Yifu Design Lab # Change this to your site name
site_description: Shared pages by Yifu
site_url: https://thinkwithpbody.github.io/YifuDesignLab # Change this to your site URL
site_author: Yifu

# nav:
#   - Projects: Projects/
#   - Guides: Guides/
#   - Wiki: Wiki/
#   - Courses: Courses/
#   - Recipes: Family/Recipe/Recipes/
#   - Projects:
#       - Project A: Courses/project-a.md
#       - Project B: projects/project-b.md

theme:
    name: 'material'
    logo: _assets/meta/logo.png
    favicon: _assets/meta/favicons.png
    custom_dir: overrides
    font:
        text: Roboto
        code: Fira Code
    # language: en
    palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: custom
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.path
        - toc.follow
        - search.suggest
        - search.highlight
# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - md_in_html
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: dataview
          class: dataview
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: folderv
          class: folderv
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      preserve_tabs: true
plugins:
  - search
  - meta-descriptions
  - awesome-pages
  - blog:
      enabled: true
      blog_dir: 'Periodic Notes' # . for blog only
      # post_dir: "{blog}/articles"
      blog_toc: true
      post_readtime_words_per_minute: 300
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: fr
      custom_format: "%A %d %B %Y"
      enable_creation_date: true
  - ezlinks:
      wikilinks: true
  - embed_file:
      callouts: true
      custom-attributes: '_static/css/custom_attributes.css'
  - custom-attributes:
      file: '_static/css/custom_attributes.css'
  - tags:
      tags_file: tags.md
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_post_page.py
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - _static/js/mathjax.js
  - _static/js/snippets.js
  - https://cdn.jsdelivr.net/gh/Enveloppe/_static@refs/heads/master/dist/index.js
  - https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - _static/css/admonition.css
    - _static/css/custom_attributes.css
    - _static/css/customization.css
    - https://cdn.jsdelivr.net/gh/Enveloppe/_static@refs/heads/master/dist/styles.css
    - stylesheets/extra.css
extra:
  SEO: '_assets/meta/logo.png'
  comments: True #disable comments globally
  generate_graph: True #generate the graph of the site
  attachments: '_assets/img/' #path to the folder where the attachments are stored
  no-auto-h1: False #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
    no_page_found: 'No pages found!' #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: true
    fix_heading: true
  icons:
    folder: "icons/" #from root _assets ; see overrides/partials/nav-item.html and overrides/partials/tabs-item.html
    default:
      file: "file.svg"
      folder: "folder-open.svg"
      index: "index.svg"
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:yifuding.twp@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yifu-ding/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/yifu_ding_/
copyright: Copyright &copy; 2025 Yifu Ding